dovecot_config_version = 2.4.0
dovecot_storage_version = 2.4.0
protocols = imap
listen = 10.77.0.20
ssl = no
auth_allow_cleartext = yes
log_path = /dev/stderr
info_log_path = /dev/stdout
mail_driver = maildir
mail_path = /srv/mail/%{user}/Maildir
mail_uid = vmail
mail_gid = vmail
first_valid_uid = 5000
passdb passwd-file {
  passwd_file_path = /srv/mail/users
}
userdb static {
  fields {
    uid = vmail
    gid = vmail
    home = /srv/mail/%{user}
  }
}
